export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_CURRENT_USER_POST_REQUEST = "GET_CURRENT_USER_POST_REQUEST";
export const GET_CURRENT_USER_POST_SUCCESS = "GET_CURRENT_USER_POST_SUCCESS";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
